### ISSUE TITLE
Make the reaction contain a command.

### ISSUE THREAD

**Issue by redstonedesigner** [TreyRuffy/CommandBlocker#1]
For example, be able to do something like:
`
Plugins:
  Message: 'Plugins (5): There. Is nothing. To. See. Here.'
  Permission: cb.allow.plugins
  Command: '/effect %player% nausea 1 60'
`

**Comment by TreyRuffy** [comment]
I will not add this at this moment.

**Comment by TreyRuffy** [comment]
I have added it in 6.0!
