### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by AnonymousBluejay** [TreyRuffy/CommandBlocker#11]
Hello, I've been using your CommandBlocker since 1.9 and it used to work great!
Unfortunately after updating past 1.14 I needed a solution to block the automatic tab completion, and the pre release isnt working that well.
I've posted these two bug reports on CommandBlocker's SpigotMC page but received no response, so I opened a issue here. Hope you see it.

This one is from about 2 weeks ago

Hello, there is a issue where tab block does not block the command itself, players cant tab in arguments but they can still press tab to see the entire list of commands, including the ones with colon even when coloned command is disabled, thus allowing them to see the server's list of plugins

I'm using version 2.0.0 beta-4 and running Paper 1.15.2

Edit:
Was able to fix coloned commands appearing in tabcomplete by changing spigot.yml, but all of the permissions from CommandBlocker doesn't work, I'm using Vault and LuckPerms (for example cb.allowcolonedcommands does not allow the user to use coloned commands)

None of the CommandBlocker's own commands work
Admins can run commands like "/cb add" one time, nothing will change, and when they try again they will get the no permission message

Also when running the /cb reload command, this error happens
https://pastebin.com/T5gFeZ6Q

This one I just posted on Spigot a few minutes ago, also leaving it here.

Another problem, a lot of commands are not getting blocked, for example

These ones are completely ignored, players can tab them in and don't get the message
//br, //brush, //desel, //deselect, //sel, //toggleplace /! and a lot more from WorldEdit
/ekit, /ewarp, /emsg, and a lot more from EssentialsX
All commands from LibsDisguises
All commands from ArmorStandEditor
All commands from Crackshot and Crackshotplus
All commands from Holograms
All commands from Multiverse
and a LOT more, there's more commands that are not blocked than ones that are blocked

Some commands cannot be tab completed but players can still run them even when they are supposed to be blocked
/,, /thru, /jump //calculate and a lot more from WorldEdit
and possibly more

Some commands gets blocked but can still be tabbed in
All of CommandBlocker's own commands
and possibly more

All of these have the same config of:
Command:
Message: '&fNope.'
Permission: cb.allow.admin
NoTabComplete: true

**Comment by AnonymousBluejay** [comment]
It cut off all the spaces I had infront of each line, I'm not sure how to add them, but the config I had was in the same format as the default config

**Comment by TreyRuffy** [comment]
Sorry I have had a lot happening to me do to COVID. I will try to fix this all ASAP.
