### ISSUE TITLE
[Bug] Member können /? eingebene und bekommen infos

### ISSUE THREAD

**Issue by toby-ger** [TreyRuffy/CommandBlocker#16]
Hallo

Member haben die Berechtigung /? das sollte geblockt sein :( und bekommen Infos über dem Server, 
obwohl das so wie es programmiert war

Bitte um Hilfe

Lg
Tobi

**Comment by TreyRuffy** [comment]
Can I please see your configuration files? And are there any errors in console?

Attempted Google Translate into German:
Versucht Google Translate:
Kann ich bitte Ihre Konfigurationsdateien sehen? Und gibt es Fehler in der Konsole?

**Comment by toby-ger** [comment]
[disabled.txt](https://github.com/TreyRuffy/CommandBlocker/files/5238755/disabled.txt)

**Comment by toby-ger** [comment]
ich hab sie als txt das es geht

**Comment by toby-ger** [comment]
der befehl wird nicht geblock = /?

**Comment by TreyRuffy** [comment]
It looks like the command was not in the blocked commands list. I added it to the bottom.

I also saved it as disabled.txt, so change the name to disabled.yml and it should work to just drag and drop it into the Command Blocker folder.

Es sieht so aus, als ob der Befehl nicht in der Liste der blockierten Befehle enthalten war. Ich habe es unten hinzugefügt.

Ich habe es auch als disabled.txt gespeichert, also ändere den Namen in disabled.yml und es sollte funktionieren, indem du es einfach per Drag & Drop in den Command Blocker-Ordner ziehst.

I added the lines:
Ich habe die Zeilen hinzugefügt:
```YAML
  ?:
    Message: '&cNo help can be provided at this time.'
    Permission: cb.allow.help
    NoTabComplete: true
```

You can download the file here:
Sie können die Datei hier herunterladen:
[disabled.txt](https://github.com/TreyRuffy/CommandBlocker/files/5242507/disabled.txt)

**Comment by TreyRuffy** [comment]
I hope that worked. If it did, just reply here and say it did! If not, tell me what's happening now.

Ich hoffe das hat funktioniert. Wenn ja, antworten Sie einfach hier und sagen Sie es! Wenn nicht, sag mir, was jetzt passiert.

**Comment by toby-ger** [comment]
HalloDanke für die Hilfe Am 22.09.2020 04:41 schrieb TreyRuffy <notifications@github.com>:
I hope that worked. If it did, just reply here and say it did! If not, tell me what's happening now.
Ich hoffe das hat funktioniert. Wenn ja, antworten Sie einfach hier und sagen Sie es! Wenn nicht, sag mir, was jetzt passiert.
