### ISSUE TITLE
[Bug] Blocking Operator Commands Does Not Work

### ISSUE THREAD

**Issue by BurnhamR** [TreyRuffy/CommandBlocker#28]
**Describe the bug**
When blocking operators' commands it does not work, whether I use in-game commands or file editing to add it.

**To Reproduce**
Install Command Blocker
Run it on the server
Add a opblock command
Try the command on an operator account
The command continues to function like normal, not blocked.

**Expected behavior**
To block the command for operators and provide the message/execute the commands.

**Desktop (please complete the following information):**
 - Server Type: Paper Spigot
 - Version: 1.16.5-788 (Latest 1.16.5 Paper Spigot)

**Additional context**
No errors in Console or On Startup.

Thanks, amazing plugin other than this issue!

**Comment by TreyRuffy** [comment]
Can you message me on Discord so I can see how your configurations are set up? Add me `TreyRuffy#2059`
