### ISSUE TITLE
/aac doesn't get blocked

### ISSUE THREAD

**Issue by NotAHackedCookie** [TreyRuffy/CommandBlocker#3]
I try to block /aac command and the command works perfectly even after disabling it. If you want I can send the plugin of the /aac command to check it. Thanks!

**Comment by TreyRuffy** [comment]
Can you send me the plugin?

**Comment by NotAHackedCookie** [comment]
https://mega.nz/#!CkF2CRDA!Npc9IZruLO9lwOuMcnZGpKn3ybATzeL5RO2uTUxGrQE

**Comment by NotAHackedCookie** [comment]
where can I send you it

**Comment by TreyRuffy** [comment]
I cannot do anything to fix it.

I believe the owner of AAC has done the same thing I have to block commands, but instead did it to enable **/aac**. You can try removing aac.version by doing adding **-aac.version** to their permissions, but I do not think it is going to work.
