### ISSUE TITLE
[Bug] Plugin Won't Start

### ISSUE THREAD

**Issue by ArcadeProgram** [TreyRuffy/CommandBlocker#38]
**Describe the bug**
Plugin won't start, and was disabled when it try to start

**Screenshots**![image](https://user-images.githubusercontent.com/85057177/189434432-f6ae0608-f778-4fe7-9173-d8cb8a6381ed.png)

**Desktop (please complete the following information):**
 - Server Type:Paper
 - Version 1.16.5

**Comment by TreyRuffy** [comment]
Try to add the command blocker legacy jar to the plugins folder and see if that fixes it.

**Comment by Arcadeprograme** [comment]
I tried to put Command Blocker V2.1.1, and this work !
But 2.1.2 doesn't work :/

**Comment by Arcadeprograme** [comment]
It doesn't matter, as long as a version works, thank you for this plugin!
