### ISSUE TITLE
Cant Block commands with Spaces!!!!

### ISSUE THREAD

**Issue by JackGamer180** [TreyRuffy/CommandBlocker#6]
please help i am really needing to block a command which contains a space ( /f claim )  but cant do it as the plugin doesn't allow you to make the blocked command contain a space please fix this or tell me how to achieve this ! ;) , PS , <3 your plugin

**Comment by MrSwalbert** [comment]
^ @TreyRuffy

**Comment by TreyRuffy** [comment]
@JackGamer180 and @MrSwalbert I believe this is in the newest version which is in the releases page.
