### ISSUE TITLE
Disable autocomplete

### ISSUE THREAD

**Issue by fjeddy** [TreyRuffy/CommandBlocker#8]
I might be completely retarded right now, but I can't seem to get the commands removed from the autocomplete list.

disabled.yml
```
DisabledCommands:
    Plugins:
        Message: none
        Permission: cb.allow.plugins
        NoTabComplete: true
    Pl:
        Message: none
        Permission: cb.allow.plugins
```

config.yml
```
# Allows you to disable tab complete!
DisableTabComplete: true
```

What on earth might I be doing wrong? Running Spigot 1.13.2

**Comment by MrAlexEsisteGia** [comment]
Is ProtocolLib installed?

**Comment by TreyRuffy** [comment]
Closing due to no response with the ProtocolLib question.
